[package]
name = "cgip"
version = "0.1.6"
edition = "2021"
repository = "https://github.com/divanvisagie/chat-gipity"
authors = ["Divan Visagie <me@divanv.com>"]
license = "Apache-2.0"
description = "Terminal client for Chat GPT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
clippy = "0.0.302"
reqwest = { version = "0.11.17", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spinners = "4.1.0"
