name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    - name: Set execution permissions
      run: chmod +x target/release/cgip
      
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/cgip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
